### ISSUE TITLE
Add Component(1) support

### ISSUE THREAD

**Issue by necolas** [reactjs/react-bower#1]
At the moment, someone else is maintaining a [Component](https://github.com/component/component)-compatible React repo: https://github.com/njpatel/react …but it's nearly identical to this, apart from having a `component.json`.

Although the name of this repo is coupled to Bower, it would be good to have Facebook officially manage the Component(1) module too.

Thanks

**Comment by gaearon** [comment]
I’m closing this as inactive. I think the community has pretty much converged at using npm for front-end libraries as it provides the desired flexibility both for CommonJS and multiple UMD builds. I encourage you to look into using npm instead. We don’t plan to support Component directly.

**Comment by necolas** [comment]
:+1:
