### ISSUE TITLE
create seperate react-with-addons bower package

### ISSUE THREAD

**Issue by lldata** [reactjs/react-bower#10]
I was using bower from https://github.com/mquandalle/meteor-bower and there is no way to specify that you need the react-with-addons package.

So that could be a limitation in meteor-bower, but Isn't it best practise to have smaller packages that 'just work'? It would seem logical if there was a separate package with just the addons, that depend on the react package.

**Comment by zpao** [comment]
That's a limitation of meteor-bower. It should probably allow you to specify which file from a package you want to use. There's a good chance you don't want the `main` file anyway (eg serving minified files in production). It does seem to mention using non-main files in the readme (https://github.com/mquandalle/meteor-bower#raw-files).

I'm not going to go out of my way to support the myriad of ways people are using bower. I think it's a flawed system.
