### ISSUE TITLE
Why not publish JSX to bower

### ISSUE THREAD

**Issue by klamtlne** [reactjs/react-bower#11]
I'm currently using browserify with reactify doing such thing, and I suppose providing JSX on bower would be another option though browserify is awesome. 

Downloading JSX from fb and create a repo, publish it to bower might be better doing by some official maintainers.

**Comment by zpao** [comment]
Not sure what you're really asking for here and you closed this. Please clarify if you actually need something.

**Comment by klamtlne** [comment]
@zpao 

I searched on bower but did not found JSX, I came here and take a glance of bower.json, still no JSX. And I wrote this issuse. 

But later I found I made a mistake, it's included. Sorry for my misbehavior.

**Comment by zpao** [comment]
No worries, glad you found it. Just wanted to make sure we weren't ignoring you.
