### ISSUE TITLE
Version 0.14.0 doesn't work

### ISSUE THREAD

**Issue by davidgomes** [reactjs/react-bower#14]
ReactDOM is undefined on the version 0.14.0 of this package.

**Comment by davidgomes** [comment]
What I did to fix this was basically copy the entire `react-dom.js` into `react.js` and now it works, but there should be a much better way around this.

**Comment by davidgomes** [comment]
After more investigation, I think your "main" in bower.json should be ["react.js", "react-dom.js"] and not just "react.js".

**Comment by nistvan86** [comment]
This modification makes transforming with browserify bad.
For eg. I've added some logging into the transformation stage and it replaces the require statement in react-dom to with an invalid javascript code.
```
  // CommonJS
  if (typeof exports === "object" && typeof module !== "undefined") {
    module.exports = f(require("./react.js")
require("./react-dom.js");
```

If i remove react-dom.js from bower.json and .bower.json of bower-react and manually add bower-dom as a separate dependency it compiles just fine.

**Comment by zpao** [comment]
This sounds like an issue that is pretty specific to your setup and unfortunately we aren't going to support every combination of tooling.

If you're already using browserify, I would suggest just using React from npm where this is a non-issue.
