### ISSUE TITLE
Visual Studio 2015 only displays up to v0.13.3

### ISSUE THREAD

**Issue by rickbeerendonk** [reactjs/react-bower#17]
Visual Studio 2015 has visual tooling to manage Bower packages in an ASP.NET Core solution. This tool only finds versions of React up to `v0.13.3` and doesn't produce result when searching for `react-dom`.

After `v0.13.3` the `version` string was removed from `bower.json` but that is what Visual Studio 2015 is using to display the available version.

**Comment by rickbeerendonk** [comment]
Visual Studio 2015 can download newer versions automatically, but you need to adjust config files that are hidden in the UI.

Best would be if Visual Studio is fixed, but let's not wait for that and make React easily available to VS2015 users.

**Comment by gaearon** [comment]
Closing as part of cleanup. If this is still an issue please let us know.
