### ISSUE TITLE
Publish the latest version v15.4.1

### ISSUE THREAD

**Issue by pvnr0082t** [reactjs/react-bower#21]
Hi @zpao @spicyj ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team and I found that the latest version v15.4.1 released on https://github.com/facebook/react. Could you please also release the latest version on this repository? Thank you.

https://github.com/cdnjs/cdnjs/issues/9782

**Comment by spicyj** [comment]
Thanks, had the commit locally but forgot to push! Done in 3f1e6e6f6221cb7658cbf9ad4ab874220c2855dd.
