### ISSUE TITLE
Why is React-Dom a part of this package?

### ISSUE THREAD

**Issue by Aghassi** [reactjs/react-bower#23]
With the move to separate React and React-Dom, I am curious as to why this package contains both. My team is currently migrating from bower to yarn and part of the issue that has arisen is adding new mappings to our legacy architecture since we now have to resolve 2 NPM packages instead of one Bower packages. I'm not expecting a change from this issue, I'm just curious about it is all :)

**Comment by oigewan** [comment]
If you go to bower.io and search for "react-dom" it comes up with something else.  In other words, I think that when they made to split, the name was taken.
