### ISSUE TITLE
React.createClass on bower

### ISSUE THREAD

**Issue by rgbkrk** [reactjs/react-bower#24]
I'm trying to migrate a project over to using React 16 that is both dependent on bower and on requirejs (heavily...). Is there any way that the old `React.createClass` could get brought in here, maybe even `prop-types`?

**Comment by gaearon** [comment]
We have no plans to publish any more code on Bower from now on.

You can aways point your Bower config to UMD builds such as:

https://unpkg.com/create-react-class@15.6.2/create-react-class.js
https://unpkg.com/prop-types@15.6.0/prop-types.js
