### ISSUE TITLE
Accessing EventPluginHub or any other internal React library from an app ?

### ISSUE THREAD

**Issue by SBRK** [reactjs/react-bower#6]
Is there a way to access EventPluginHub, that you would get with require("react/lib/EventPluginHub") in a react project, in an app that uses react-bower ? 
When calling require.list(), EventPluginHub is nowhere to be found and it's not in window or in React.addons either.

**Comment by gaearon** [comment]
No, there is no way to access the library internals from the UMD builds. In general it’s discouraged as those are not parts of the public API, and may change significantly without warnings. I understand that some third-party plugins would like to inject into the event system but we don’t currently officially support this. Your best bet is either to avoid such plugins, or to do this via the CommonJS build on npm at your own risk. Sorry that I don’t have a better solution for you! Cheers.
